// Code generated by core.gen.go.tmpl. DO NOT EDIT.

// authors nyhu,contributors

package tmpl

import (
	"fmt"
	"github.com/spf13/cast"
	"reflect"
)

func Testing(kind reflect.Kind, value interface{}) {
	switch kind {
	case reflect.Float64:
		fmt.Println("float64", cast.ToFloat64(value))
	case reflect.Int:
		fmt.Println("int", cast.ToInt(value))
	case reflect.Int64:
		fmt.Println("int64", cast.ToInt64(value))
	case reflect.String:
		fmt.Println("string", cast.ToString(value))
	case reflect.Bool:
		fmt.Println("bool", cast.ToBool(value))
	default:
		panic(fmt.Errorf("unhandled type %v", kind))
	}
} // fmt is automatically run and correct file discrepancies
