name: CI

on: [push, pull_request]

jobs:
  current-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run tests
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          bash -c ./scripts/test.sh
